name: End-to-end tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-Cy_Portfolio:    
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress Run Tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./Cypress_Portfolio