name: End-to-end tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-Cy_Portfolio:    
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress Run Tests
        uses: ./
        with:
          working-directory: Cypress_Portfolio