name: KarateCI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  run_KarateAPI_Graduation_Tests: 

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
       java-version: '17'
       distribution: 'adopt'

    - name: Installing Maven
      run: |
       cd KarateAPI_Graduation
       mvn clean install

    - name: Running Tests   
      run: |
       cd KarateAPI_Graduation
       mvn test -Dtest=RunAllTests
    
    - name: Getting Artifacts
      uses: actions/upload-artifact@v4
      with:
       name: report
       path: ./KarateAPI_Graduation/target/karate-reports/karate-summary.html


  run_KarateAPI_Portfolio_Tests:    

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
       java-version: '17'
       distribution: 'adopt'

    - name: Installing Maven
      run: |        
        cd KarateAPI_Portfolio        
        mvn clean install
  
    - name: Running Tests   
      run: |
       cd KarateAPI_Portfolio
       mvn test -Dtest=RunAllTests

    - name: Getting Artifacts
      uses: actions/upload-artifact@v4
      with:
       name: report
       path: ./KarateAPI_Portfolio/target/karate-reports/karate-summary.html
