name: KarateCI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  preparing_enviroment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

  run_KarateAPI_Graduation_Tests:
    needs: preparing_enviroment
    runs-on: ubuntu-latest
    steps:
    - name: Installing Maven
      run: |
       cd KarateAPI_Graduation
       mvn clean install

    - name: Run Tests   
      run: mvn test -Dtest=RunAllTests

  run_KarateAPI_Portfolio_Tests:
    needs: preparing_enviroment
    runs-on: ubuntu-latest
    steps:
    - name: Installing Maven
      run: |
        cd KarateAPI_Portfolio
        mvn clean install
  
    - name: Run Tests   
      run: mvn test -Dtest=RunAllTests