name: KarateCI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  run_KarateAPI_Graduation_Tests: 

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
       java-version: '17'
       distribution: 'adopt'

    - name: Installing Maven
      run: |
       cd KarateAPI_Graduation
       mvn clean install

    - name: Run Tests   
      run: |
       ls -la
       cd KarateAPI_Graduation
       ls -la  
       mvn test -Dtest=RunAllTests


  run_KarateAPI_Portfolio_Tests:    

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
       java-version: '17'
       distribution: 'adopt'

    - name: Installing Maven
      run: |        
        cd KarateAPI_Portfolio        
        mvn clean install
  
    - name: Run Tests   
      run: |
       ls -la  
       cd KarateAPI_Portfolio
       ls -la
       mvn test -Dtest=RunAllTests
