name: PostmanCI

on:
  push:
      branches: ["main"]

jobs:
  tests_postmanAPI:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Step 1 Check version Newman and Note
      run: |
        newman --version
        node --version

    - name: Step 2 Install Newman-Report-Htmlextra
      run: sudo npm install -g newman-reporter-htmlextra

    - name: Step 3 Execute collection
      run: newman run ./Postman/serverestAPI.json -e ./Postman/serverestEnv.json --reporters cli, -r htmlextra --reporter-htmlextra-export ./results/Report.html
    
    - name: Step 4 Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: report
        path: ./results/Report.html
